# sample: dotnet add package LiteDB --version 5.0.1
name: dotnetcore-webapp-dependency-review

on:
  pull_request:
    branches:
      - main
  #push:
  #  branches: 
  #    - main
  #    - feature/*
  #  paths-ignore:
  #    - 'docs/**'
  #    - '.github/**'
  workflow_dispatch:

env:
  CONFIGURATION: Release

permissions: 
  pull-requests: write
  
jobs:
  dependency-review:
    runs-on: 
      labels: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
      
    - name: Restore dependencies
      run: dotnet restore src/MyFirstProject.sln
    
    - name: Build
      run: dotnet build src/MyFirstProject.sln --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Test
      run: dotnet test src/MyFirstProject.Tests/MyFirstProject.Tests.csproj --no-build --configuration ${{ env.CONFIGURATION }} --verbosity normal --logger "junit;LogFilePath=TestResults/tests.xml"
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        comment-summary-in-pr: always
        deny-licenses: MIT
